name: firebase_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.9
  url_launcher: ^6.0.9
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^9.0.0 
  http: ^0.13.3
  flutter_typeahead: ^4.0.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^14.0.1
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true
 
